apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      initContainers:
      - name: busybox  
        image: busybox
        command: ['sh', '-c', 'cp /home/bm10/app-jenkins/jenkins-laravel/.env /var/www/html/'] 
        volumeMounts:
        - mountPath: /var/www/html
          name: v1
      containers:
      - name: myapp-container
        image: mo1074/laravel-jenkins:${BUILD_NUMBER}
        volumeMounts:
        - mountPath: /var/www/html
          name: v1
        ports:
        - containerPort: 80
          name: http
      volumes:
      - name: v1
        hostPath: 
          path: /home/bm/k8s 
