apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp  
  template:
    metadata:
      labels:
        app: myapp  
    spec:
      containers:
      - name: myapp-container  
        image: mo1074/laravel-jenkins:${BUILD_NUMBER}
        ports:
        - containerPort: 80
          name: http  
