apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment 
  labels:
    app: myapp
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: myapp 
  template:
    metadata:
      labels:
        app: myapp
    spec:
      initContainers:
      - name: copy-env
        image: busybox
        command:
        - sh
        - -c
        - cp /config/.env /var/www/html/.env
        volumeMounts:
        - mountPath: /config
          name: config-volume
        - mountPath: /var/www/html
          name: app-volume
      containers:
      - name: myapp-container
        image: mo1074/laravel-jenkins:25
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/html
          name: app-volume
      volumes:
      - name: config-volume
        configMap:
          name: myapp-config
      - name: app-volume
        hostPath:
          path: /mnt
        
        
